project:
  type: website
  output-dir: _site
execute: 
  warning: false
  freeze: auto

website:
  title: "Simulasi Bisnis Digital"
  page-navigation: true
  back-to-top-navigation: true
  navbar: false
  reader-mode: true
  

  page-footer:
      left: |
        An open-source platform for macroeconomic model simulation. 
      right: |
        <a>License: ...<a/> <a href="https://github.com/hermantoXYZ/Simulasi-Makro#">Source code</a>


  sidebar:
    style: "docked"
    title: "Simulasi Bisnis Digital"
    search: true
    numbered: true
    
    tools: 
      - icon: twitter
        href: https://twitter.com/hermantoXYZ
      - icon: github
        href: https://github.com/hermantoXYZ


    contents:
      - text: "Introduction"
        href: index.qmd

      - section:  "Getting Started"
        contents:
          - getting_started.qmd


      - section: "Agency"
        contents:
          - digital_agency.qmd
          - agency_report.qmd
      - section: "Client"
        contents:
          - strategy_breakdown_template.qmd
          - digital_clients.qmd
      - section: "Tools"
        contents:
          - tools.qmd


format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    toc-depth: 5
    number-depth: 2
    code-fold: true
    code-summary: "Show code"
    code-link: true
    code-copy: true
    number-sections: true
    
  


